[package]
name = "shape-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
darling = "0.20.10"
paste = "1.0.15"
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.89"