[package]
name = "shape"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "2.6.0"
serde_json = "1.0.133"
shape-macros = { path = "../shape-macros" }

[dev-dependencies]
regex = "1.11.1"
regex_static = "0.1.1"
serde = { version = "1.0.215", features = ["derive"] }
text-diff = "0.4.0"
